image: nodejs
branches:
  - main
matrix:
  - env: SCRIPT=lint
  - env: SCRIPT=typecheck
install:
  - npm ci
script:
  - npm run $SCRIPT
jobs:
  - image: nodejs
    stage: deploy
    branches:
      - tags/*
    install:
      - npm ci
    script:
      - npm run build
      - npm set registry https://registry.npmjs.org
      - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish
