image: nodejs
branches:
  - master
  - tags/*
matrix:
  - env: SCRIPT=lint
  - env: SCRIPT=typecheck
install:
  - npm ci
script:
  - npm run $SCRIPT
deploy:
  - npm ci
  - npm run build
  - >
    if [ -z "$ABSTRUSE_TAG" ]; then
      npm set registry https://registry.npmjs.org
      npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      npm publish
    fi
