port: 8700
agents:
  - type: android
    startAppCommand: echo "TEST!!!"
    startAppTimeout: 30000
    output: screenshots/android
    paths:
      adb: ~/Android/platform-tools/adb
      emulator: ~/Android/emulator/emulator
      sdkManager: ~/Android/cmdline-tools/latest/bin/sdkmanager
      avdManager: ~/Android/cmdline-tools/latest/bin/avdmanager
    devices:
      - pixel_4;28
      - pixel_c;26
    clearNotifications: true
    time: 1610352398
  - type: ios
    startAppCommand: npm run ios
    startAppTimeout: 900000
    output: screenshots/ios
    devices:
      - com.apple.CoreSimulator.SimDeviceType.iPhone-7;com.apple.CoreSimulator.SimRuntime.iOS-10–3
    time: 1610352398
